[versions]
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.1"
quilt_loader = "0.19.1"

quilted_fabric_api = "7.0.3+0.83.1-1.20.1"
terraformersmc_modmenu = "7.1.0"
limlib = "8.1.8"
specialmodels = "1.2.5"

cloth = "11.0.99"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

terraformersmc_modmenu = { module = "com.terraformersmc:modmenu", version.ref = "terraformersmc_modmenu" }

ludocrypt_limlib = { module = "com.github.LudoCrypt:Liminal-Library", version.ref = "limlib" }
ludocrypt_specialmodels = { module = "com.github.LudoCrypt:Special-Models", version.ref = "specialmodels" }

shedaniel_cloth = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth" }

[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
